global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'inventory-ms'
    metrics_path: /inventory-ms/actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          app: 'inventory-ms'

  - job_name: 'logistics-ms'
    metrics_path: /logistics-ms/actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          app: 'logistics-ms'

  - job_name: 'orders-ms'
    metrics_path: /orders-ms/actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          app: 'orders-ms'

  - job_name: 'payments-ms'
    metrics_path: /payments-ms/actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          app: 'payments-ms'

  - job_name: 'search-ms'
    metrics_path: /search-ms/actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          app: 'search-ms'

  - job_name: 'users-ms'
    metrics_path: /users-ms/actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          app: 'users-ms'
